### ISSUE TITLE
DevOpsDays Texas

### ISSUE THREAD

**Issue by jjasghar** [developeravocados/developeravocados.github.io#102]
DevOpsDays Texas - https://devopsdays.org/events/2021-texas/welcome/
CFP: https://links.devopsdaystx.org/cfp
Deadline: Jan 31st
Location: Virtual online
Date: March 2nd, 3rd
Travel & Accommodation: Discord/YouTube :metal:
Code of Conduct: https://links.devopsdaystx.org/coc

**Comment by AlexLakatos** [comment]
Thanks for submitting this!
