### ISSUE TITLE
🆔 Identity, Unlocked... Explained: Season 2, Ep. 1

### ISSUE THREAD

**Issue by robertinoc** [developeravocados/developeravocados.github.io#103]
[🆔 Identity, Unlocked... Explained: Season 2, Ep. 1](https://auth0.com/blog/identity-unlocked-explained-season-2-ep-1/?utm_source=content_synd&utm_medium=sc&utm_campaign=identity_unlocked) - @auth0
🛡Torsten Lodderstedt joins the podcast today to talk about his work on Financial-Grade API (FAPI) WG.

**Comment by AlexLakatos** [comment]
Hey @robertinoc. Thanks for contributing to the newsletter. We try really hard to curate articles, videos and podcasts published in the week prior to the newsletter publish day, which is always a Monday. Could we ask you that moving forward to try to submit only content that fits that 8-day window?

The content we're looking for is helping people get better/into Developer Relations, those tend to be less about the tech and more about the journeys.

**Comment by robertinoc** [comment]
Ok @AlexLakatos thanks for your heads up!
