### ISSUE TITLE
Data Love

### ISSUE THREAD

**Issue by idabzo** [developeravocados/developeravocados.github.io#104]
Data Love - https://datalove.konfy.care
CFP: https://www.papercall.io/datalove
Deadline: March 7th
Location: Virtual online
Date: April 16th
Travel & Accommodation: Discord/Zoom & SpatialChat
Code of Conduct: https://berlincodeofconduct.org

**Comment by AlexLakatos** [comment]
Thanks! We've already included this CFP in our newsletter a couple of weeks ago. https://tinyletter.com/developeravocados/letters/launching-a-developer-champion-program-103
