### ISSUE TITLE
A video that explains what it means to be a Developer Advocate, and how to follow this career path!

### ISSUE THREAD

**Issue by seemcat** [developeravocados/developeravocados.github.io#105]
[So you want to be a Developer Advocate?](https://www.youtube.com/watch?v=JtVn0sitWuk&t=7s) - @seemcat created a fun and comprehensive video that answers what a Developer Advocate is, what they do, and how YOU can follow this career path starting today!

**Comment by AlexLakatos** [comment]
Thanks for submitting your video! We loved it!

**Comment by seemcat** [comment]
Yay! Thank you. So happy you loved it 🥳
