### ISSUE TITLE
PyCon AU 2019

### ISSUE THREAD

**Issue by glasnt** [developeravocados/developeravocados.github.io#11]
PyCon AU - https://2019.pycon-au.org/
CFP: https://2019.pycon-au.org/speak/ 
Deadline: May 5 2019, Anywhere on Earth (+12 UTC)
Location: Sydney, Australia
Date: 2 - 6 August 2019
Travel & Accommodation: https://2019.pycon-au.org/assistance/
Code of Conduct: https://2019.pycon-au.org/conduct/

**Comment by AlexLakatos** [comment]
put this in today's issue, thanks for contributing 💌
