### ISSUE TITLE
Using Twitter questions to build a parallel community

### ISSUE THREAD

**Issue by garethx** [developeravocados/developeravocados.github.io#113]
[Using Twitter questions to build a parallel community](https://orbit.love/blog/using-twitter-questions-to-build-a-picture-of-your-community/) -[@OrbitModel](https://twitter.com/OrbitModel)
A practical guide on using Twitter questions to build a better community.

**Comment by AlexLakatos** [comment]
Thanks for sharing the article. It's a great one, but we try really hard to only feature articles published in the previous week, so this one would have been a perfect candidate for the issue we sent yesterday.
