### ISSUE TITLE
The Big Transaction - New Orleans, LA

### ISSUE THREAD

**Issue by joeellis** [developeravocados/developeravocados.github.io#125]
The Big Transaction - https://www.thebigtransaction.com
CFP: https://www.papercall.io/the-big-transaction
Deadline: July 15th, 2021
Location: New Orleans, LA
Date: November 4th-5th, 2021
Travel & Accommodation: We provide a travel stipend to assist all speakers!
Code of Conduct: https://www.thebigtransaction.com/policies/

**Comment by AlexLakatos** [comment]
It made it into today's issue of the newsletter!
