### ISSUE TITLE
DevFest WI CFP

### ISSUE THREAD

**Issue by abraham** [developeravocados/developeravocados.github.io#13]
DevFest WI - https://devfestwi.com
CFP: https://forms.gle/sapi9R2o1yWQcXeA6
Deadline: June 30th, 2019
Location: Madison, WI
Date: Sept 28th, 2019
Travel & Accommodation: Selected speakers that need travel/Accommodations will have it covered.
Code of Conduct: https://devfestwi.com/coc

**Comment by AlexLakatos** [comment]
Thanks for submitting, put this in Issue 32.
