### ISSUE TITLE
Et tu, booth?

### ISSUE THREAD

**Issue by colmdoyle** [developeravocados/developeravocados.github.io#131]
[Et tu, booth?](https://cdoyle.me/posts/2021/05/et-tu-booth) - [Colm Doyle](https://twitter.com/colmisainmdom)

Is a conference booth really the best way to engage with developers? And if it isn't, why do we spend so much time and money on them?

**Comment by AlexLakatos** [comment]
Thanks for submitting! It made Issue 116 of the newsletter. https://tinyletter.com/developeravocados/letters/should-community-managers-know-how-to-babysit-116
