### ISSUE TITLE
A day in the life of a Cloud Advocate

### ISSUE THREAD

**Issue by weeyin83** [developeravocados/developeravocados.github.io#142]
🥑 [A Day in the Life of a Cloud Advocate](https://dev.to/techielass/a-day-in-the-life-of-a-cloud-advocate-4f0c) 

A fun look at what a Cloud Advocate's day looks like.

**Comment by AlexLakatos** [comment]
Thanks for submitting! It made it into issue 120 of the newsletter. https://tinyletter.com/developeravocados/letters/tech-career-developer-relations-and-blogging-120
