### ISSUE TITLE
Configure Windows Package Manager Settings

### ISSUE THREAD

**Issue by weeyin83** [developeravocados/developeravocados.github.io#148]
[Configure Windows Package Manager Settings](https://www.techielass.com/configure-windows-package-manager-settings/)

Join me as I look at the settings file for the Windows Package Manager and see what I can configure!

**Comment by AlexLakatos** [comment]
Thanks for submitting. It's a great resouce. It doesn't really fit the content strategy for our DevRel audience, so we're going to pass on it for the newsletter.
