### ISSUE TITLE
Installing software with Windows Package Manager

### ISSUE THREAD

**Issue by weeyin83** [developeravocados/developeravocados.github.io#152]
[Installing software with Windows Package Manager](https://www.techielass.com/installing-software-with-windows-package-manager/)

Let's take a look at how you can use Windows Package Manager to install software on your computer.

**Comment by AlexLakatos** [comment]
Thanks for submitting. It's a great resource. It doesn't really fit the content strategy for our DevRel audience (mostly devrel related resources), so we're going to pass on it for the newsletter.
