### ISSUE TITLE
What is Developer Relations?

### ISSUE THREAD

**Issue by weeyin83** [developeravocados/developeravocados.github.io#153]
[What is Developer Relations?](https://www.techielass.com/what-is-devrel/)

Let's take a look at a Cloud Advocate's definition and explanation of what Developer Relations is.

**Comment by AlexLakatos** [comment]
Thanks for submitting! It's a great article, I've added it to our curation list for next week.

**Comment by AlexLakatos** [comment]
It was published in Issue 122! Thanks again for submitting it!
