### ISSUE TITLE
New post "Advices for junior conference speakers"

### ISSUE THREAD

**Issue by nfrankel** [developeravocados/developeravocados.github.io#16]
Hello,

Please consider publishing in your next newsletter the following post:

[Advices for junior conference speakers](https://blog.frankel.ch/advices-junior-conference-speakers/) - @nicolas_frankel

>Some years ago, I started my journey on the conference circuit. I did that on my own, in my free time. Without mentorship on how to do that, and with my gut feeling as the only guidance, I made plenty of mistakes…​ and I still regularly do. However, I now have a couple of hard-earned experience years behind me.
>
>In this post, I’d like to offer some advices that might be of interest if you want to start your own journey and have no available mentor. Please don’t consider them as rules, but they just happened to work for me.

Thanks!

**Comment by AlexLakatos** [comment]
Thanks for sharing the article. It made it in today's newsletter. https://tinyletter.com/developeravocados/letters/developer-avocados-weekly-issue-52

**Comment by nfrankel** [comment]
I saw that, many thanks!
