### ISSUE TITLE
Upcoming Browser Behavior Changes: What Developers Need to Know

### ISSUE THREAD

**Issue by RamiroND** [developeravocados/developeravocados.github.io#18]
[Upcoming Browser Behavior Changes: What Developers Need to Know](https://auth0.com/blog/browser-behavior-changes-what-developers-need-to-know/) - @auth0
Learn everything you need to know about Browser Behavior Changes and the implications for your web applications.

**Comment by AlexLakatos** [comment]
Thanks for submitting the issue, it's great content but not really for our audience.
