### ISSUE TITLE
Lead Dev London 2020

### ISSUE THREAD

**Issue by EvelinaRoman** [developeravocados/developeravocados.github.io#20]
Lead Dev London 2020 - https://wvnts.co/2RyOVZd
CFP: https://wvnts.co/2RwWy2a
Deadline: 13 January 2020
Location: Barbican Centre, London
Date: 24-25 June 2020
Travel & Accommodation: Included
Code of Conduct: https://wvnts.co/36dMFdO

**Comment by AlexLakatos** [comment]
Thanks for sending us the CFP!
