### ISSUE TITLE
How To Take Over An Existing Project

### ISSUE THREAD

**Issue by flippedcoder** [developeravocados/developeravocados.github.io#21]
[How To Take Over An Existing Project](https://dev.to/flippedcoding/how-to-take-over-an-existing-project-3hg5) - @FlippedCoding Taking over a project can feel a little stressful because there are a lot of unknowns you are walking into. At the beginning of every project, I try to ask these questions and they've helped me tremendously. Hopefully they'll be useful for you too!

**Comment by AlexLakatos** [comment]
Thanks for submitting the content!
