### ISSUE TITLE
Creating Your First Laravel App and Adding Authentication

### ISSUE THREAD

**Issue by Bachiauth0** [developeravocados/developeravocados.github.io#22]
[Creating Your First Laravel App and Adding Authentication](https://auth0.com/blog/creating-your-first-laravel-app-and-adding-authentication) - @auth0 
By popular demand, we have updated one of our most popular Authentication Tutorials! Now you can:
- Learn the basics of #Laravel
- Integrate Auth0 into your Laravel app.

**Comment by AlexLakatos** [comment]
Thanks for sending the article in. It's a great article, but I don't think it fits with our audience of Developer _Advocates_.
