### ISSUE TITLE
How to be a good speaker

### ISSUE THREAD

**Issue by facundomr** [developeravocados/developeravocados.github.io#23]
[How to be a good speaker](https://medium.com/@facundomr/how-to-be-a-good-speaker-c51a64820a5c?source=friends_link&sk=ac5555bfd17151177622ad5d0da825c2) - @facundomr Some tips on how to be a better speaker, based on author's personal experience as a speaker and event organizer.

**Comment by AlexLakatos** [comment]
Thanks for sending the article in. It's a great article!
