### ISSUE TITLE
StrapiConf 2022: Open Source Headless CMS - 2nd Global User Conference

### ISSUE THREAD

**Issue by ShadaW11** [developeravocados/developeravocados.github.io#239]
Conference_Name - Conference_URL: StrapiConf 2022 - https://conf.strapi.io/
CFP: https://strp.cc/3IbfHPh
Deadline: December 2021
Location: Online
Date: March 16
Travel & Accommodation: - 
Code of Conduct: https://forum.strapi.io/faq#coc

**Comment by AlexLakatos** [comment]
Thanks. This made it into last week's newsletter. https://tinyletter.com/developeravocados/letters/the-state-of-developer-relations-2021-report-146

**Comment by ShadaW11** [comment]
@AlexLakatos Thank youuuuuuuuuu
