### ISSUE TITLE
Developer's Guide to Common Vulnerabilities and How to Prevent Them

### ISSUE THREAD

**Issue by Bachiauth0** [developeravocados/developeravocados.github.io#24]
[Developer's Guide to Common Vulnerabilities and How to Prevent Them](https://auth0.com/blog/developers-guide-to-common-vulnerabilities-and-how-to-prevent-them/) - @auth0 
Learn how to prevent common vulnerabilities such as XSS, injection, and third-party vulnerabilities

**Comment by AlexLakatos** [comment]
Thanks for sending the article in. It's a great article, but I don't think it fits with our audience of Developer _Advocates_.
