### ISSUE TITLE
The DevRel toolkit for API providers

### ISSUE THREAD

**Issue by tsolakoua** [developeravocados/developeravocados.github.io#246]
[Tools](https://dev.to/tsolakoua/the-devrel-toolkit-for-api-providers-2aop) we use as a DevRels on a daily basis for an API program.

**Comment by AlexLakatos** [comment]
Thanks for sharing! Sadly, it's a little late to make it into next week's newsletter. We try to curate the articles, videos, and podcasts published in the week prior to the newsletter publish day. We try really hard to use content that fits that 8-day window. 

Please do send things our way in the future as soon as it "hits the press", this was a great article, and we're sad we've missed it.

**Comment by tsolakoua** [comment]
I completely understand, thanks for the quick feedback @AlexLakatos!
