### ISSUE TITLE
THAT Conference Call for Counselors

### ISSUE THREAD

**Issue by brettski** [developeravocados/developeravocados.github.io#25]
THAT Conference - https://www.thatconference.com
CFP: https://www.thatconference.com/wi/call-for-counselors
Deadline: 02/29/2020
Location: Wisconsin Dells, WI
Date: August 3, 2020 - August 6, 2020
Travel & Accommodation: https://www.thatconference.com/wi/counselor-handbook
Code of Conduct: https://www.thatconference.com/wi/code-of-conduct

**Comment by AlexLakatos** [comment]
Thank you for the CFP, it's going out in today's newsletter.
