### ISSUE TITLE
Lead Dev San Francisco 2020

### ISSUE THREAD

**Issue by EvelinaRoman** [developeravocados/developeravocados.github.io#26]
Lead Dev San Francisco 2020 - https://wvnts.co/3aQKkJ8
CFP: https://wvnts.co/36EaT0G
Deadline: March 23, 2020
Location: San Francisco, CA
Date: October 7-8, 2020
Travel & Accommodation: Included
Code of Conduct: https://wvnts.co/2U5dbn6

**Comment by AlexLakatos** [comment]
@EvelinaRoman thank you for the CFP, it's going out in today's newsletter. In the future, please use the plain, non-tracking URLs, pretty please 😁
