### ISSUE TITLE
Developer Relations in 2022 - Where I'm focusing

### ISSUE THREAD

**Issue by colmdoyle** [developeravocados/developeravocados.github.io#262]
[Developer Relations in 2022 - Where I'm focusing](https://cdoyle.me/posts/2022/01/devrel-in-2022-my-focus) - @colmisainmdom

What does 2022 hold for Developer Advocacy? There's two big things I know my team will focus on, and I think most of the industry is likely to be thinking along the same lines, so I've shared them here.

**Comment by AlexLakatos** [comment]
Thanks for sharing!
