### ISSUE TITLE
🤔 How Developers Will Work in 2022?

### ISSUE THREAD

**Issue by robertinoc** [developeravocados/developeravocados.github.io#264]
[🤔 How Developers Will Work in 2022?](https://auth0.com/blog/how-developers-will-work-in-2022/?utm_source=content_synd&utm_medium=sc&utm_campaign=career) - @auth0
From tooling changes to the ascent of the hybrid event model, it’s all change, all the time.

**Comment by AlexLakatos** [comment]
Thanks for sharing!
