### ISSUE TITLE
JavaScript and Friends Conference 2022

### ISSUE THREAD

**Issue by baskarmib** [developeravocados/developeravocados.github.io#265]
JavaScript and Friends Conference 2022 - [Conference_URL](https://www.javascriptandfriends.com/)
CFP: https://sessionize.com/javascript--friends-conference-2022
Deadline: Feb-13-2022 11:59 PM US EST
Location: Columbus, Ohio
Date: July-29-2022
Travel & Accommodation: No
Code of Conduct: https://www.javascriptandfriends.com/codeofconduct

**Comment by AlexLakatos** [comment]
Thanks for sharing!
