### ISSUE TITLE
Jbcnconf 

### ISSUE THREAD

**Issue by jonathanvila** [developeravocados/developeravocados.github.io#268]
JBCNConf - @jbcnconf 
CFP:1st January 2022
Deadline: April 30th, 2022
Location: Barcelona, Spain
Date: 18-20 July 2022
Travel & Accommodation: small budget
Code of Conduct:https://www.jbcnconf.com/2022/coc.html

**Comment by AlexLakatos** [comment]
Thanks for sharing!
