### ISSUE TITLE
The Developer’s Guide to Content Creation Book

### ISSUE THREAD

**Issue by rubymorillo** [developeravocados/developeravocados.github.io#27]
Title: The Developer’s Guide to Content Creation
Content Type: Book
Link: https://www.developersguidetocontent.com
Author: Stephanie Morillo
Twitter: @radiomorillo

Description: Today's developers are content creators. Developers regularly write blog posts, create courses, launch podcasts, screencasts, and more to share what they know with other devs. The sheer amount of content has made learning the craft of software development more accessible to more people. There's just one thing missing: your voice!

If you've ever wanted to start a blog in order to:

- Document what you're learning
- Improve your writing skills
- Teach others
- Showcase what you know to potential employers
- Move into a different role

...this book is for you! 

The Developer's Guide to Content Creation will show you how to manage the content process from ideation to promotion. You'll learn how to develop a persona for your blog, a blog mission statement, and a content calendar. You'll learn four ways to generate ideas for new posts, and you'll learn best practices for creating written content that promotes readability and accessibility. You'll also learn how to pitch and write for tech publications you admire.

Each chapter includes short exercises and accompanying worksheets that you can use and reuse at any point in your journey. The guide includes a list of essential tools, resources, and books for the serious content creator.

**Comment by rubymorillo** [comment]
@AlexLakatos new content issue for your consideration. Thanks in advance!

**Comment by AlexLakatos** [comment]
Hi @rubymorillo, this doesn't really fit our current content strategy. We usually do free articles, videos and podcasts released in the past week. We did do book promotions in the past as sponsored content, so let me know if that's something you'd want to look into.

**Comment by rubymorillo** [comment]
Hey @AlexLakatos completely understood; thank you for letting me know! Closing out this issue.
