### ISSUE TITLE
LeadDev London 2022

### ISSUE THREAD

**Issue by EvelinaRoman** [developeravocados/developeravocados.github.io#276]
LeadDev London 2022 - [Conference_URL](https://leaddev.com/leaddev-london)
CFP: https://leaddev.submittable.com/submit/a4dd65ac-e237-4f64-b596-46eab61d9180/leaddev-london-2022-call-for-proposals
Deadline: Feb 14
Location: London
Date: June 7-8
Travel & Accommodation: Yes
Code of Conduct: https://leaddev.com/code-conduct

**Comment by AlexLakatos** [comment]
Thanks for submitting this. Sadly, the deadline has closed before our next issue goes out today. We'd love it if next time you submit a conference you'd allow for 10-14 days before the deadline closes.

**Comment by EvelinaRoman** [comment]
Thank you Alex, it was indeed submitted late and appreciate the update.
We'll aim to have these submitted ahead of time next round.

Many thanks and have a great week,
Evelina
