### ISSUE TITLE
What is Content Design with Amy Burns

### ISSUE THREAD

**Issue by Linda-Ikechukwu** [developeravocados/developeravocados.github.io#278]
[What is Content Design with Amy Burns](https://www.everythingtechnicalwriting.com/content-design-with-amy-burns/) - @_MsLinda chatted with Amy Burns who recently just transitioned to a Senior Content Designer role at GitHub on what content design is, and how her new role supports developer experience.

**Comment by AlexLakatos** [comment]
Thanks for submitting this. Unfortunately, we try really hard to add only resources published in the last 7 days to the newsletter, and this looks to have been released in December. Please do send the third installment in the series as soon as it's published, looking forward to seeing who you've interviewed this month!
