### ISSUE TITLE
Documentation made nicer with visuals

### ISSUE THREAD

**Issue by Tallyb** [developeravocados/developeravocados.github.io#28]
[Documentation made nicer with visuals](https://dev.to/tallyb/documentation-made-nicer-with-visuals-1pfm) -
@baraktally gives some tips on how to make your documentation clear and shiny by adding visuals and diagrams

[Title](url) - @twitter_username summary of the article / video / podcast

**Comment by AlexLakatos** [comment]
Thanks for the submission, it's going to be in today's newsletter!
