### ISSUE TITLE
How to write content that users will actually read, based on learnings from user psychology

### ISSUE THREAD

**Issue by Linda-Ikechukwu** [developeravocados/developeravocados.github.io#288]
[How to write content that users will actually read, based on learnings from user psychology](https://www.everythingtechnicalwriting.com/how-to-write-content-that-readers-will-read/) - @_mslinda talks about how to tailor your articles to align with how users read on the web, in order to capture their attention and increase their chances of reading them.

**Comment by AlexLakatos** [comment]
Thanks for sharing. Your website seems to be down, with error `Internal Server Error - Request ID: 01FXQKXFNQ7M5N2EYEKVT5448N`

**Comment by Linda-Ikechukwu** [comment]
That's weird. Please check if it's fixed now. It's showing up just right on my devices.

**Comment by AlexLakatos** [comment]
Yeah, seems to be back online now.
