### ISSUE TITLE
From Staff Technical Writer To Developer Advocate; Read Amruta Ranade’s Story

### ISSUE THREAD

**Issue by Linda-Ikechukwu** [developeravocados/developeravocados.github.io#289]
[From Staff Technical Writer To Developer Advocate; Read Amruta Ranade’s Story](https://www.everythingtechnicalwriting.com/from-staff-technical-writer-to-developer-advocate-read-amruta-ranades-story/) - @_mslinda sat down with Amruta, who is a Staff Technical Writer at Airbyte to talk about her transition from Staff Technical Writer to Developer Advocate back to Staff Technical Writer, and what she learned.

**Comment by AlexLakatos** [comment]
Thanks for sharing! Your website seems to be down though, it errors when I try to access the link with `Internal Server Error - Request ID: 01FXQKDXAZNF00T8G918F35STV`
