### ISSUE TITLE
LeadDev San Francisco 2022

### ISSUE THREAD

**Issue by EvelinaRoman** [developeravocados/developeravocados.github.io#296]
LeadDev San Francisco 2022 - [Conference_URL](https://leaddev.com/leaddev-san-francisco)
CFP: https://leaddev.submittable.com/submit/7c2c8da9-17e3-483d-961b-a97e977093bb/leaddev-san-francisco-2022-call-for-proposals
Deadline: April 29
Location: San Francisco
Date: October 25-27
Travel & Accommodation: Yes
Code of Conduct: https://leaddev.com/code-conduct

**Comment by AlexLakatos** [comment]
Thanks for sharing! We'll add it to Monday's newsletter.
