### ISSUE TITLE
LeadDev Berlin 2022

### ISSUE THREAD

**Issue by EvelinaRoman** [developeravocados/developeravocados.github.io#297]
LeadDev Berlin 2022 - [Conference_URL](https://leaddev.com/leaddev-berlin)
CFP: https://leaddev.submittable.com/submit/9d57534a-1130-42df-82e2-f8992d7a1a6b/leaddev-berlin-2022-call-for-proposals
Deadline: April 29
Location: Berlin
Date: November 2-4
Travel & Accommodation: Yes
Code of Conduct: https://leaddev.com/code-conduct

**Comment by AlexLakatos** [comment]
Thanks for sharing! We'll add it to Monday's newsletter.
