### ISSUE TITLE
Article Suggestion

### ISSUE THREAD

**Issue by gabogaldino** [developeravocados/developeravocados.github.io#304]
Hi!
I am a regular reader of your Newsletter and also a professional in the area of Developer Relations. I recently developed an article giving tips on my first 3 months in the area, based on several articles and conversations with other professionals who helped me during this journey: https://bit.ly/3OB0Twz
I would be very happy if you share it in the NewsLetter, because it can help other people too.
Thank you very much!

**Comment by AlexLakatos** [comment]
Thanks for sending this our way! It was great!
