### ISSUE TITLE
Developer Insights Germany 2020

### ISSUE THREAD

**Issue by franciedf** [developeravocados/developeravocados.github.io#31]
[Developer Insights Germany 2020](https://fh-digital.org/developer-insights-germany-2020/) -  [Franziska Hauck](https://twitter.com/_francied) crunched the numbers for developers and IT professionals in Germany and found that, when it comes to diversity, the country has a long way to go.

**Comment by AlexLakatos** [comment]
Thanks for submitting this, it's a really good read!

**Comment by franciedf** [comment]
Thank you, happy to hear that!
