### ISSUE TITLE
API The Docs Virtual 2022

### ISSUE THREAD

**Issue by KlaudiaJancsovics** [developeravocados/developeravocados.github.io#313]
API The Docs is a conference space dedicated to API documentation and developer portals. The conference series is organized by Pronovix since 2016, virtual since 2020. The events are for techwriters, product owners, developer relations engineers: members of API teams who want to deep dive in API documentation and explore how it relates to a great developer experience. 

API The Docs 2022 is a series of **four real time online events**, taking place **on the Wednesdays of 21 September, 12 & 26 October, 9 November (15-18 UTC)**.

API The Docs Virtual 2022 - [apithedocs.org](https://apithedocs.org/)
CFP: Talks are expected to be 20 minutes in duration, informative and providing the results of your research, development, and best practices. API The Docs is a techstack- and vendor neutral knowledge sharing space. Restrict any marketing of products and services to a minimum (for example a brief mention, links for more information). All API The Docs events are recorded and published online. 

Topics could be covered: 

- API strategy & governance and how they relate to API documentation
- UX focused API design & great developer experience design (best practices, new trends, tools)
- API description languages & API publication solutions (use cases, trends, best practices, challenges & solutions)
- Documenting non-REST API formats (GraphQL, Kafka Streams, AsyncAPI, SOAP)
- API references with additional content (use cases, trends, best practices)
- Business documentation on API portals & BizDevOps
- Devportals at scale: change management on large & complex API documentation sets (case studies)
- API lifecycle and your devportal
- Publishing workflows for API documentation
- DocOps, Docs as Code, CI/CD on your developer portal (case studies)
- Community management and developer relations in the API economy

You can send your proposal [here](https://www.papercall.io/atd-virtual-2022). 

Deadline: CFP closes at June 30, 2022 20:00 UTC
Location: online event
Date: 21 September, 12 & 26 October, 9 November
Code of Conduct: We follow the ground rules of the [Write The Docs community](https://www.writethedocs.org/code-of-conduct/): be friendly, be respectful, be careful in the words that you choose. If you need to report any issue for a reason, please contact info@apithedocs.org. All reports will be kept confidential.

![facebook](https://user-images.githubusercontent.com/106378527/170952124-1c2dee13-27d4-4573-928c-306a22ab8dad.jpg)

**Comment by AlexLakatos** [comment]
Thanks for sending this our way! We'll put the CFP in today's newsletter!
