### ISSUE TITLE
How to handle managers who do not understand the technical writing role

### ISSUE THREAD

**Issue by Linda-Ikechukwu** [developeravocados/developeravocados.github.io#322]
[How to handle managers who do not understand the technical writing role](https://www.everythingtechnicalwriting.com/debunking-popular-technical-writing-misconceptions/) - @_MsLinda Elisa Sawyer who is a Documentation Architect with over 20 years of extensive technical writing experience talks about what to do when you find yourself working with managers who don't understand the role of technical writers, and also debunked some popular technical writing myths.

**Comment by AlexLakatos** [comment]
Thanks for your PR!
