### ISSUE TITLE
A Technical Writer's Introduction To Docs As Code

### ISSUE THREAD

**Issue by Linda-Ikechukwu** [developeravocados/developeravocados.github.io#323]
[A Technical Writer's Introduction To Docs As Code](https://www.everythingtechnicalwriting.com/dosc-as-code/) - @_mslinda 
 Learn what you need to know to set up docs-as-code for your documentation team to foster better collaboration between writers and developers.

**Comment by AlexLakatos** [comment]
Thanks for your PR!
