### ISSUE TITLE
2023 Google Season of Docs now open! 

### ISSUE THREAD

**Issue by emckean** [developeravocados/developeravocados.github.io#369]
[Announcing Google Season of Docs 2023!](https://opensource.googleblog.com/2023/01/announcing-google-season-of-docs-2023.html) - @GoogleOSS The 2023 Google Season of Docs program has now launched! In Google Season of Docs, open source projects can apply for grants to hire technical writers directly to create, update, and improve their documentation and developer experience. Technical writers interested in participating can find more information in the [Technical Writer guide](https://developers.google.com/season-of-docs/docs/tech-writer-guide) on the Google Season of Docs site.

**Comment by AlexLakatos** [comment]
Thanks for the submission!
