### ISSUE TITLE
Developer Evangelists 🚀 — DevRelCarousels #4

### ISSUE THREAD

**Issue by yashovardhan** [developeravocados/developeravocados.github.io#37]
Hey there!

As a part of my DevRelCarousels series, today I published the next issue. Feel free to check out it out

I hope you all like it 😄 

Alongside this, if you're planning to post this on twitter, I would love to have this gif animation included as well: 
![Developer-Evangelists](https://user-images.githubusercontent.com/21066442/87860333-32846b00-c95a-11ea-8724-0dfb2ff3e22c.gif)

[Developer Evangelists 🚀 — DevRelCarousels #4](https://medium.com/@yashovardhana/developer-evangelists-devrelcarousels-4-299f80cc1d36) - @yashovardhan 

DevRelCarousels is targeted towards including beginners into DevRel. In this blog and carousel series, I tried to give an overview of what a Developer Evangelist job really is. 

All of my carousels are available on my this [Instagram channel](https://www.instagram.com/developerelations/) as well.

**Comment by AlexLakatos** [comment]
This made it to the newsletter, thanks for sharing!
