### ISSUE TITLE
Auth0 Hackathon

### ISSUE THREAD

**Issue by robertinoc** [developeravocados/developeravocados.github.io#40]
[Auth0 Hackathon](https://auth0.com/blog/auth0-hackathon/?utm_source=newsletter&utm_medium=sc&utm_campaign=auth0_hackathon) - @auth0 
We are very excited to announce our first-ever hackathon! We’ve got 6 superb partners, $10,000 worth of prizes, and the best developers in the world (you) hacking with us to solve some very real issues.

**Comment by AlexLakatos** [comment]
Hi Robert,

This feels more like something that would be sponsored content. Here's some info on how those work: https://developeravocados.net/sponsor-us/

Cheers,
