### ISSUE TITLE
Submission suggestion

### ISSUE THREAD

**Issue by efortuna** [developeravocados/developeravocados.github.io#400]
[Compensating Actions, Part of a Complete Breakfast with Sagas](https://temporal.io/blog/compensating-actions-part-of-a-complete-breakfast-with-sagas) - @bouncingsheep How do you handle failure that spans more than one microservice? Learn about the Compensating Action Design Pattern for distributed systems

Hi there! This article is more "to keep up on industry terminology in a user-friendly way" than DevRel ideology but hopefully it's useful.

**Comment by AlexLakatos** [comment]
Thanks for sharing! We'll add it to the curation queue.

**Comment by efortuna** [comment]
Thank you!
