### ISSUE TITLE
Article Contribution: My Journey As A Community Intern

### ISSUE THREAD

**Issue by adityaoberai** [developeravocados/developeravocados.github.io#49]
[My Journey As A Community Intern](https://medium.com/progate/my-journey-as-a-community-intern-7c75f7d4eafa?source=friends_link&sk=c2a87fcaa4b85cfe13c9b1814ca0a95a) - @adityaoberai1 

How I Spent 5 Months Empowering Student Tech Communities With Progate

**Comment by AlexLakatos** [comment]
Thanks for submitting, this made it into last weeks newsletter!
