### ISSUE TITLE
LeadDev Live Winter 2020

### ISSUE THREAD

**Issue by whiteoctevents** [developeravocados/developeravocados.github.io#51]
LeadDev Live 2020- https://bit.ly/3cy2H72
CFP: https://bit.ly/3cy2H72
Deadline: October 25
Location: Online / Virtual
Date: December 2
Travel & Accommodation: N/A
Code of Conduct: https://bit.ly/330asiG

**Comment by AlexLakatos** [comment]
Thanks for submitting, it's made it into today's newsletter.
