### ISSUE TITLE
Contribution to the newsletter

### ISSUE THREAD

**Issue by ukmadlz** [developeravocados/developeravocados.github.io#8]
Requires a page to submit contributions to the newsletter.

Should possibly include a guide to suitable material and formats.

**Comment by ukmadlz** [comment]
I think @AlexLakatos wants to do this as an Issue Template, which would be a lot easier than what I had in mind.

**Comment by AlexLakatos** [comment]
Finally got around to it. The repo has 3 issue templates now, with CTAs on https://developeravocados.net/contribute/
