### ISSUE TITLE
What is Developer Experience and Why you should care

### ISSUE THREAD

**Issue by DominikMilaniak** [developeravocados/developeravocados.github.io#95]
[What is Developer Experience and Why you should care](https://medium.com/dx-heroes/what-is-developer-experience-and-why-you-should-care-e0bbdb114981) - [@DX_Heroes](https://twitter.com/DX_Heroes) - Developer Experience is an emerging industry you don't want to sleep on. Only happy developers can deliver world-class products. In this article you will find out what DX is and how to better it in your company.

**Comment by AlexLakatos** [comment]
Thanks, we already had the link in one of our issues.
